// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4paTCgwOjWLe3OYu2uXxV7X0A6JLiNc',
    appId: '1:202586376542:web:a6d302b1932185392ee7cf',
    messagingSenderId: '202586376542',
    projectId: 'izistock',
    authDomain: 'izistock.firebaseapp.com',
    storageBucket: 'izistock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdlKjG40jff6vJ0t2gfJgBcAJ27AlMy9s',
    appId: '1:202586376542:android:68f4985941c695002ee7cf',
    messagingSenderId: '202586376542',
    projectId: 'izistock',
    storageBucket: 'izistock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDxNFo7zO8QEYQ2E7HcMW2Pqw5P46TJW4',
    appId: '1:202586376542:ios:85289e3e1a7b422c2ee7cf',
    messagingSenderId: '202586376542',
    projectId: 'izistock',
    storageBucket: 'izistock.appspot.com',
    iosClientId: '202586376542-gq2c3vh1iu47hrjdkk500r5q5b2l5ih8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoJava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDxNFo7zO8QEYQ2E7HcMW2Pqw5P46TJW4',
    appId: '1:202586376542:ios:2c191b690d0611e32ee7cf',
    messagingSenderId: '202586376542',
    projectId: 'izistock',
    storageBucket: 'izistock.appspot.com',
    iosClientId: '202586376542-jbh5v5i3h16h516501hcoikaodqjb90r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoJava.RunnerTests',
  );
}
